"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Ticket = { public_number: string; requester_name: string | null; requester_email: string | null; requester_phone: string | null; status: string; priority: string; subject: string; customer_message: string; ai_summary: string; delivery_status: string; created_at: string; updated_at: string; support_messages?: Array<{ sender_type: string; message: string; is_internal: boolean; created_at: string }> };

export default function SupportTicketPage({ params }: { params: Promise<{ id: string }> }) {
  const [ticket, setTicket] = useState<Ticket | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [reply, setReply] = useState("");
  useEffect(() => { void params.then(({ id }) => fetch(`/api/admin/support/${encodeURIComponent(id)}`).then((response) => response.json()).then((payload) => payload.data ? setTicket(payload.data) : setError(payload.error || "Не найдено"))); }, [params]);
  async function update(status: string) { if (!ticket) return; setSaving(true); const response = await fetch("/api/admin/support", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ publicNumber: ticket.public_number, status }) }); const payload = await response.json(); if (response.ok) setTicket({ ...ticket, status: payload.data.status }); else setError(payload.error || "Ошибка"); setSaving(false); }
  async function sendReply() { if (!ticket || !reply.trim()) return; setSaving(true); const response = await fetch("/api/admin/support", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ publicNumber: ticket.public_number, message: reply.trim() }) }); if (response.ok) { setTicket({ ...ticket, support_messages: [...(ticket.support_messages ?? []), { sender_type: "manager", message: reply.trim(), is_internal: false, created_at: new Date().toISOString() }] }); setReply(""); } else { const payload = await response.json(); setError(payload.error || "Ошибка"); } setSaving(false); }
  if (error) return <p className="text-rose-200">{error}</p>; if (!ticket) return <p className="text-slate-400">Загрузка...</p>;
  return <div className="max-w-3xl space-y-6"><Link href="/admin/support" className="text-sm text-cyan-200">← Все обращения</Link><div className="rounded-2xl border border-white/10 bg-slate-900/70 p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-cyan-300">{ticket.public_number}</p><h2 className="mt-2 text-2xl font-semibold text-white">{ticket.subject}</h2></div><p className="text-sm text-slate-400">{ticket.status} · {ticket.priority}</p></div><dl className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Клиент</dt><dd className="text-white">{ticket.requester_name || "Гость"}</dd></div><div><dt className="text-slate-500">Контакт</dt><dd className="text-white">{ticket.requester_email || ticket.requester_phone || "Не указан"}</dd></div></dl><div className="mt-6 rounded-xl bg-white/5 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Сообщение клиента</p><p className="mt-2 whitespace-pre-wrap text-slate-200">{ticket.customer_message}</p></div><div className="mt-4 rounded-xl bg-cyan-300/5 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">AI summary</p><p className="mt-2 text-slate-200">{ticket.ai_summary}</p></div>{ticket.support_messages?.filter((message) => !message.is_internal).map((message, index) => <div key={index} className="mt-4 rounded-xl bg-white/5 p-3"><p className="text-xs text-slate-500">{message.sender_type}</p><p className="mt-1 text-sm text-slate-200">{message.message}</p></div>)}<textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Ответить клиенту" aria-label="Ответить клиенту" className="mt-6 min-h-28 w-full rounded-xl border border-white/10 bg-slate-950/60 p-3 text-sm text-white" /><button disabled={saving || !reply.trim()} onClick={() => void sendReply()} className="mt-2 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">Отправить ответ</button><div className="mt-6 flex flex-wrap gap-2"><button disabled={saving} onClick={() => void update("in_progress")} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">Принять</button><button disabled={saving} onClick={() => void update("waiting_for_client")} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-slate-200 disabled:opacity-50">Ожидать клиента</button><button disabled={saving} onClick={() => void update("resolved")} className="rounded-xl border border-emerald-300/30 px-4 py-2 text-sm text-emerald-200 disabled:opacity-50">Решено</button></div></div></div>;
}
