"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Ticket = { public_number: string; requester_name: string | null; category: string; priority: string; status: string; subject: string; delivery_status: string; created_at: string };
type TelegramStatus = { configured: boolean; url: string; pending_update_count: number; last_error_date: number | null; last_error_message: string | null; max_connections: number | null; allowed_updates: string[] };

function TelegramStatusBlock() {
  const [telegramStatus, setTelegramStatus] = useState<TelegramStatus | null>(null); const [setupSecret, setSetupSecret] = useState(""); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const fetchStatus = () => fetch("/api/admin/telegram/webhook/status").then(async (response) => { const payload = await response.json().catch(() => null); if (response.status === 403) { setTelegramStatus(null); return; } if (!response.ok || !payload?.data) throw new Error(payload?.error || "Не удалось проверить Telegram"); setTelegramStatus(payload.data as TelegramStatus); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Не удалось проверить Telegram")).finally(() => setLoading(false));
  const loadStatus = () => { setLoading(true); setError(""); void fetchStatus(); };
  useEffect(() => { void fetchStatus(); }, []);
  if (!loading && !telegramStatus && !error) return null;
  const setup = () => { setWorking(true); setError(""); void fetch("/api/admin/telegram/webhook/setup", { method: "POST", headers: { "Content-Type": "application/json", "x-telegram-webhook-setup-secret": setupSecret }, body: "{}" }).then(async (response) => { const payload = await response.json().catch(() => null); if (!response.ok || !payload?.status) throw new Error(payload?.error || "Не удалось настроить webhook"); setTelegramStatus(payload.status as TelegramStatus); setSetupSecret(""); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Не удалось настроить webhook")).finally(() => setWorking(false)); };
  return <section className="rounded-2xl border border-cyan-200/15 bg-slate-950/50 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Telegram</p><h3 className="mt-2 text-xl font-semibold text-white">Статус интеграции</h3></div><button type="button" onClick={loadStatus} disabled={loading || working} className="rounded-xl border border-white/10 px-3 py-2 text-sm text-slate-200 disabled:opacity-50">Проверить статус</button></div>{loading ? <p className="mt-4 text-sm text-slate-400">Проверка...</p> : telegramStatus ? <div className="mt-4 grid gap-3 text-sm text-slate-300 sm:grid-cols-2"><p>Telegram: <strong className="text-white">{telegramStatus.configured ? "подключён" : "не подключён"}</strong></p><p>Webhook: <strong className={telegramStatus.last_error_message ? "text-amber-300" : "text-emerald-300"}>{telegramStatus.last_error_message ? "ошибка" : telegramStatus.configured ? "активен" : "не настроен"}</strong></p><p>Pending updates: <strong className="text-white">{telegramStatus.pending_update_count}</strong></p><p>Последняя ошибка: <strong className="text-white">{telegramStatus.last_error_message || "нет"}</strong></p><div className="sm:col-span-2 flex flex-wrap gap-2"><input type="password" value={setupSecret} onChange={(event) => setSetupSecret(event.target.value)} placeholder="Setup secret" autoComplete="off" className="min-w-64 rounded-xl border border-white/10 bg-slate-900 px-3 py-2 text-sm text-white placeholder:text-slate-500" /><button type="button" onClick={setup} disabled={!setupSecret || working} className="rounded-xl bg-cyan-300 px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">Настроить webhook</button></div></div> : null}{error ? <p role="alert" className="mt-4 text-sm text-amber-300">{error}</p> : null}</section>;
}

export default function SupportPage() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { void fetch(`/api/admin/support${status ? `?status=${encodeURIComponent(status)}` : ""}`).then((response) => response.json()).then((payload) => setTickets(payload.data ?? [])).finally(() => setLoading(false)); }, [status]);
  return <div className="space-y-6"><TelegramStatusBlock /><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.2em] text-cyan-300">Opero Support</p><h2 className="mt-2 text-3xl font-semibold text-white">Обращения к менеджеру</h2></div><select value={status} onChange={(event) => { setLoading(true); setStatus(event.target.value); }} className="rounded-xl border border-white/10 bg-slate-900 px-3 py-2 text-sm text-white"><option value="">Все обращения</option><option value="open">Новые</option><option value="in_progress">В работе</option><option value="waiting_for_client">Ожидают клиента</option><option value="resolved">Решённые</option></select></div>{loading ? <p className="text-slate-400">Загрузка...</p> : <div className="overflow-hidden rounded-2xl border border-white/10"><div className="divide-y divide-white/10">{tickets.map((ticket) => <Link key={ticket.public_number} href={`/admin/support/${ticket.public_number}`} className="block p-4 transition hover:bg-white/5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-cyan-200">{ticket.public_number}</p><p className="mt-1 text-white">{ticket.subject}</p><p className="mt-1 text-xs text-slate-400">{ticket.requester_name || "Гость"} · {ticket.category} · {ticket.priority}</p></div><div className="text-right text-xs text-slate-400"><p>{ticket.status}</p><p>{new Date(ticket.created_at).toLocaleString("ru-RU")}</p></div></div></Link>)}{tickets.length === 0 ? <p className="p-6 text-slate-400">Обращений пока нет.</p> : null}</div></div>}</div>;
}
