alter table if exists public.apartments
  add column if not exists type text,
  add column if not exists google_link text,
  add column if not exists city text,
  add column if not exists district text,
  add column if not exists address text,
  add column if not exists latitude text,
  add column if not exists longitude text,
  add column if not exists short_desc text,
  add column if not exists rooms integer,
  add column if not exists bedrooms integer,
  add column if not exists bathrooms integer,
  add column if not exists floor integer,
  add column if not exists area numeric,
  add column if not exists max_guests integer,
  add column if not exists price text,
  add column if not exists deposit numeric,
  add column if not exists cleaning_fee numeric,
  add column if not exists rental_types jsonb not null default '{}'::jsonb,
  add column if not exists daily_price numeric,
  add column if not exists weekly_price numeric,
  add column if not exists monthly_price numeric,
  add column if not exists minimum_nights integer,
  add column if not exists minimum_weeks integer,
  add column if not exists minimum_months integer,
  add column if not exists owner_name text,
  add column if not exists owner_phone text,
  add column if not exists owner_email text,
  add column if not exists responsible_user_id uuid references auth.users(id) on delete set null,
  add column if not exists backup_manager_user_id uuid references auth.users(id) on delete set null,
  add column if not exists status text,
  add column if not exists availability text,
  add column if not exists publish_status text,
  add column if not exists publication_status text,
  add column if not exists bookings integer not null default 0,
  add column if not exists cover_photo_url text;